export const GET_STORED_PRODUCT_LIST = 'GET_STORED_PRODUCT_LIST';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const FILTER_RESULTS = 'FILTER_RESULTS';
